name: Textile Hive Zine
favicon: null
layout_spectrum: 0.26109
typography_spectrum: 0.5891316859051585
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#061041'
    - '#ffffff'
    - '#afb2c4'
    - '#5b6387'
    - '#d5d7e1'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
